apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - image: korage/udagram-reverseproxy
        name: reverseproxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "1000Mi"
            cpu: "350m"
          limits:
            memory: "1500Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always