language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for loggin
  - docker image prune -f -a
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag backend-feed docker_hub/udagram-api-feed
  - docker tag backend-user docker_hub/udagram-api-user
  - docker tag frontend:local docker_hub/udagram-frontend
  - docker tag reverseproxy docker_hub/udagram-reverseproxy

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose -f docker-compose-build.yaml push
  
