language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag ./udagram-api-feed/udagram-api-feed docker_hub/udagram-api-feed:latest
  - docker tag ./udagram-api-user/udagram-api-user docker_hub/udagram-api-user:latest
  - docker tag ./udagram-frontend/udagram-frontend docker_hub/udagram-frontend:latest
  - docker tag ./udagram-reverseproxy/udagram-reverseproxy docker_hub/udagram-reverseproxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose -f docker-compose-build.yaml push
  
